### ISSUE TITLE
Can't start timhaak/plex

### ISSUE THREAD

**Issue by schubby** [timhaak/docker-plex#102]
Hello timhaak, 

Fisrt of all thank you very much for your image timhaak/plex. I use it for 15 months and i love it 😃 

My actual docker "server" is an old laptop and i am changing it

With the same image timhaak/plex in my 2 environnements, i don't have same result for the same "docker run"
`docker run --restart=always \
    -d --name plex \
    -h http://schubby.ddns.net \
    -v /home/PlexConfig:/config \
    -v /mnt/Maxell:/data \
    -p 32400:32400 timhaak/plex`

On my old server it work for 15  months like i said. but here is the result on my new server
`find: '/config': Permission denied
mkdir: cannot create directory '/config/Library': Permission denied
cp: cannot create regular file '/config/Library/Application Support/Plex Media Server/Preferences.xml': No such file or directory
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
mkdir: cannot create directory '/config/Library': Permission denied
WARNING COULDN'T CREATE /config/Library/Application Support, MAKE SURE I HAVE PERMISSON TO DO THAT!`

I tried to chmod and chown my folder /home/PlexConfig
I tried to create foders and file "/config/Library/Application Support/Plex Media Server/Preferences.xml"
I trier to "push" my image to docker hub, and "pull" it on my new server
but nothing change

In both cases, i have 2 fedora server up to date
old server : 
* Fedora server 24
* Docker Version:         1.10.3

New server :
* Fedora server 27
*Docker  Version:         1.13.1

Do you have an idea ?? 

Schubby

**Comment by timhaak** [comment]
Hi

Try using the env variable RUN_AS_ROOT

Ie -e RUN_AS_ROOT=TRUE

**Comment by schubby** [comment]
I forgot to mention, i tried that too 

I don't really understand if my probem is le container or in my server.
The message let understand "/config" so in the container.

So, i tried something like create a container running it with "-it [...] /bin/bash"
In there, itried somethink like 'chmod 777 /config', commit in a new images. I have no more error message but it doesn't work for the moment. I continue trying in that direction

**Comment by schubby** [comment]
Hey Timhaak, 

On my new server, i didn't configure SELINUX. It was my problem ^^

Thank's again

**Comment by timhaak** [comment]
Glad you solved it :)
