### ISSUE TITLE
No longer works with "-u" argument

### ISSUE THREAD

**Issue by miloshpetrov** [timhaak/docker-plex#103]
Hello!

Until recently, I was able to run the container like this:
`docker run -u "1234:1234" timhaak/plex`

But after updating to the latest image, it stopped working, with the following error:
`s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied`

Maybe it's possible to add environment variables that would specify the UID and GID of a user that runs plex? E.g.:
`docker run -e "P_UID=1234" -e "P_GID=1234" timhaak/plex`

Thank you!

**Comment by timhaak** [comment]
I'm not going to have time to look until this weekend at the earliest.

If you would like it sooner you could send a push request?

**Comment by miloshpetrov** [comment]
Thanks for looking at it! I might try sending a push request on Monday, if it's still actual by that time.

**Comment by miloshpetrov** [comment]
Ah, looks like the plexinc/pms-docker already has such feature. This seems to be the solution:
`docker run -e 'PLEX_UID=1234' -e 'PLEX_GID=1234' timhaak/plex`
