### ISSUE TITLE
Can't read directory /data after update

### ISSUE THREAD

**Issue by Fridus** [timhaak/docker-plex#15]
```
d---------   6 root root    4096 Apr 13 20:57 data
```

After few seconds:
```
/# ls -l
total 92
drwxr-xr-x   2 root root    4096 Apr 13 21:07 bin
drwxr-xr-x   2 root root    4096 Dec 24 13:41 boot
drwxr-xr-x   4 plex nogroup 4096 Apr 13 20:53 config
drwxrwxrwx   6 root root    4096 Apr 13 20:57 data

/# su plex
plex@xyz:/$ ls -l /data
ls: cannot open directory /data: Permission denied
```

**Comment by timhaak** [comment]
Hi

I had someone else request that I don't run plex as root.

I can do change ownership on start (I'm doing it for the config) but was worried would mess peoples files up.

Though think its a rights permission problem on the data folder.

Could you try doing 

chmod -R a+rX /data

Or the directory that you mount data from. It should make all the directories visible especially the root one and readable. 

I think most likely problem is that the base directory is readable.

**Comment by Fridus** [comment]
I use `docker exec -it plex-server bash` for enter into the docker.
Try to see the directory change the permission O_o
```
plex@FloNUC:/$ ls -l /data/
total 28
drwxrwxrwx 6 1026 users 16384 Jan 31 00:13 Movies
drwxrwxrwx 9 1026 users  4096 Mar  2 20:36 Series
plex@FloNUC:/$ ls -l /data/Series/
ls: cannot open directory /data/Series/: Permission denied
plex@FloNUC:/$ ls -l /data/
total 28
drwxrwxrwx 6 1026 users 16384 Jan 31 00:13 Movies
drwx------ 9 1026 users  4096 Mar  2 20:36 Series
```

**Comment by timhaak** [comment]
Did you try and run chmod -R a+rX /data ?

**Comment by Fridus** [comment]
Yes, this doesn't work.

I think that is since this commit 4d0e756af8866bc405b766e7ed10cd198818a463
My directory `data` is mounted in nfs from my NAS. :/

**Comment by Fridus** [comment]
Ok it's since this commit.
I've solved the bug by switching my NFS user on admin.

Thx a lot !

**Comment by donvipre** [comment]
i have the same issue now.
data is stored on the host with root as owner.
the container user plex can't access it.
What should i do?

**Comment by timhaak** [comment]
For now I'm going to revert the change. I'll put more thought into solving it over the weekend.

**Comment by timhaak** [comment]
I've pushed the change. If you pull in about 30 minutes it should start working again.

I'll spend some time this weekend thinking about a more correct fix.

**Comment by Fridus** [comment]
It was my NAS that not allow to browse the folder `data` because It was not the root user, but plex user.
Your folder must to have the correct permissions and if you use NFS, activate the option "all user are like admin". So the permission applied to `/data` are respected.

**Comment by timhaak** [comment]
Yes more going to see if I can some for of warning or something clever with the docker images to tell people.

**Comment by timhaak** [comment]
Meant to add

In the mean time for moved it to run plex as root so less technical people don't get burnt.

Will have something more correct this weekend.
