### ISSUE TITLE
How to update PMS

### ISSUE THREAD

**Issue by keepitshut** [timhaak/docker-plex#16]
Hi Tim,
first off id like to thank you for this docker file its been working like a charm. my plex tells me that there is an update available, how do i update my pms version? thank you

**Comment by timhaak** [comment]
Simplest method is to pull the new version the restart

ie 
```
docker pull timhaak/plex
docker stop <container_name_or_id>
docker rm <container_name_or_id>
docker run <what you normall put here>
```

**Comment by adampetrovic** [comment]
Alternatively, I have tagged the docker plex image under my own namespace (due to the nightmare of things breaking with the recent root permission changes).

This means you can run:

```
$ docker exec -t -i <container_name> /bin/bash
# apt-get update && apt-get dist-upgrade
# exit
$ docker commit <container_name> <plex image name>
```

**Comment by timhaak** [comment]
I like that option :)

An alternate option is to use a docker file similar to

https://github.com/timhaak/docker-plex-update/blob/master/Dockerfile

Still not sure what the correct answer is for the root problem.

If anyone has any idea's of how to handle this in a sane way for the majority of people using this.

https://github.com/timhaak/docker-plex/issues/17
