### ISSUE TITLE
Find a way to not run plex as root and allow read on a directory for most users.

### ISSUE THREAD

**Issue by timhaak** [timhaak/docker-plex#17]
Putting this here for a couple brain storm ideas around handling this.

If you have any ideas please shout.

**Comment by timhaak** [comment]
Here are a couple options I'm thinking about.

1. Have a flag to set non root. So people who know how to handle the problem can choose to not run as root.
2. Have the image do chmod a+Xr on the data directory.
3. Have the above but only run with a flag or have  a flag to disable this ability.
4. Create a separate image that is a gui for starting the container and can allow fo starting containers and checking rights on a directory. Also is a way to handle updates.

**Comment by justintime** [comment]
I just made a PR for a 5th option.

On bootup, determine the GID of the /data volume, and ensure that the plex user is part of that group.  This will work even if the permissions are changed on the host machine (after a container restart).

**Comment by timhaak** [comment]
Thanks :)

Been a bit busy this side but have leave starting Friday so will go over this then.

**Comment by timhaak** [comment]
I've added the pull request.

Though I've left it running as root for now (Though it can now be set to not root with an environment variable. )

I've also started tagging the builds.

**Comment by marcoamorales** [comment]
Hey @timhaak, thanks for your work on this!

I'm looking to run Plex as a non root user and was wondering which were the reasons that you decided to run this as root initially.

**Comment by timhaak** [comment]
Not really great reasons but basically broke down to it being simpler and it solved the problem of people having the files owned by a user that did not give read rights to plex.

The with the current docker image you can set environment variables to make it not run as root.

use RUN_AS_ROOT=false and possibly CHANGE_DIR_RIGHTS=true

You can check the start.sh file to see what exactly they do if your interested.

I had planned to do some more testing around this hopefully to make it the default but life has been a bit to busy this side.

**Comment by sirlancelot** [comment]
supervisord has a an option to run the child process as a certain user. [`[program:x] options`](http://supervisord.org/configuration.html#program-x-section-example)

**Comment by timhaak** [comment]
Yup. Though the person who was originally complaining about root rights wanted supervisord also running as non root.

**Comment by joswart** [comment]
For me the solution was to have a modified version of /etc/group in my /config folder and mount it with -v during docker run.

This way, I can easily control the access of the plex user, so it can access my media. It also survives upgrades of the docker image.

As a side note: I have done the same for the start.sh script. The one you provide does a chmod on the /config directory. Since I have plex set to generate preview pictures of my media, my Library is around 140Gb and the chmod just kills my startup times. The one I use puts a remark in front of the chmod.

**Comment by timhaak** [comment]
Closing this for now due to time constraints
