### ISSUE TITLE
This is installing an old version

### ISSUE THREAD

**Issue by yankees9920** [timhaak/docker-plex#19]
It looks like this dockerfile is installing server version 0.9.8.18 from Dec 24, 2013, rather than the latest. It would be great if this could be configured to pull down the latest official release from plex.

Great work, thanks!

**Comment by yankees9920** [comment]
error on my part, i was hitting an old plex instance I had installed locally.

**Comment by yankees9920** [comment]
However it does seem to still be installing an older version (not as old as I originally thought) - Version 0.9.11.7 from Dec 22, 2014

**Comment by timhaak** [comment]
Hi

I just did a pull and restart and I'm getting 0.9.11.16. When did you last pull the image?

Docker unfortunately doesn't automatically pull updates to images. 

Also if your wanting to get the latest version you can pull timhaak/plexpass though you may need the plex pass to use it. 

Generally the images should be at most one day out of what is available at http://shell.ninthgate.se/packages/debian.
