### ISSUE TITLE
Plex version 0.9.12.0.1071 is out.

### ISSUE THREAD

**Issue by kurron** [timhaak/docker-plex#20]
Plex version 0.9.12.0.1071 is out.  Any chance of getting an image update to pull that in?

Thanks,
Ron

**Comment by bhavicp** [comment]
You realize that the docker side of things has nothing to do with the version? When you pull the image, it builds the latest version of Plex available from the Debian repo. You will simply have to wait for the maintainer of that repo to put 0.9.12 into the repo and then pull/build the image as it's not maintained by Plex themselves.

**Comment by timhaak** [comment]
Ah almost. When you pull it pulls the last built version. It doesn't build at the moment. 

I have it set to rebuild once a night so worst case the build will be one day old.

Having said that if you don't do a pull it won't give the latest version. 

Just checked mines at the latest version (0.9.12.0). 

So try just doing a pull.
