### ISSUE TITLE
Doesnt seem to get past initalisation

### ISSUE THREAD

**Issue by microadam** [timhaak/docker-plex#22]
Hello,

Have been running a much older version of this docker image for a while. Trying to update to the latest one.

I have stopped the old container, pulled the latest version and created a new container pointing at my existing config directory.

```
docker run -d --name plex --restart always -h plex.domain.co.uk -v /var/plex:/config -v /media:/data -p 32400:32400 timhaak/plex
```

First time I run the container I get this:

```
docker logs plex
+ GROUP=plextmp
+ mkdir -p /config/logs/supervisor
+ chown -R plex: /config
```

However, this is all I get, even on subsequent runs (restart of the container, stop and start etc). It just repeats the same 3 lines over and over on every run.

Any thoughts as to what the issue might be?

**Comment by timhaak** [comment]
Could you try the following.

docker run -it --rm {your normal settings here} timhaak/plex /bin/bash

Then run

/start.sh

Can you see an error ?

**Comment by microadam** [comment]
Some more progess, with some errors!

```
+ GROUP=plextmp
+ mkdir -p /config/logs/supervisor
+ chown -R plex: /config
+ touch /supervisord.log
+ touch /supervisord.pid
+ chown plex: /supervisord.log /supervisord.pid
+ rm -rf /var/run/lock /var/run/motd.dynamic /var/run/sendsigs.omit.d /var/run/shm /var/run/utmp
+ rm -f '/config/Library/Application Support/Plex Media Server/plexmediaserver.pid'
+ mkdir -p /var/run/dbus
+ chown messagebus:messagebus /var/run/dbus
+ dbus-uuidgen --ensure
+ dbus-daemon --system --fork
+ sleep 0.2
+ avahi-daemon -D
Timeout reached while wating for return value
Could not receive return value from daemon process.
```

Looks like an issue with avahi?

**Comment by microadam** [comment]
Tried running `avahi-daemon` manually in the container and get this error:

```
Found user 'avahi' (UID 102) and group 'avahi' (GID 103).
Successfully dropped root privileges.
chroot.c: fork() failed: Resource temporarily unavailable
failed to start chroot() helper daemon.
```

**Comment by microadam** [comment]
So I managed to get it working.

I had to change `/etc/avahi/avahi-daemon.conf` to have `enable-dbus=no` and then modify `start.sh` to have `avahi-daemon -D --no-drop-root`

All seems to be working now! (I can connect from plex web and stream things at least)

Not sure what impact this might have though?

**Comment by timhaak** [comment]
Odd. 

Though I have a feeling we don't need to install avahi independently anymore as I think plex has something built in.

Will try and test this coming weekend. 

I'll also testing your changes and if they work on my side (Should :) )

Will add it to the default.

**Comment by bhavicp** [comment]
I got this same error today after updating my image to the latest version. Seems to be related to https://github.com/lxc/lxc/issues/25

**Comment by timhaak** [comment]
Hmm. I'll have a look over the weekend properly this week is a bit busy. Will if there is something we can do once I have time to properly understand what the problems is.

**Comment by pryorda** [comment]
If you remove the rm -rf /var/run/* from the start file it will run fine. Not sure if this is a valid solution, but it works for me.

**Comment by timhaak** [comment]
Sorry didn't have time last weekend and away next. Will look at it when I get some time.

**Comment by timhaak** [comment]
I've just removed that and a bit more that looks like it isn't needed any more.

Seems to be working on my side but please test once the docker servers have rebuilt the images.
