### ISSUE TITLE
Multiple Plex Instances

### ISSUE THREAD

**Issue by delaman** [timhaak/docker-plex#23]
Currently I am not able to run more than one docker-plex on a given server.  I am sharing a dedicated server and need to be able to run two or more docker-plex at any giving time.

I believe currently the supervisor setup does not allow more than one docker-plex.  Is this the case?

Please allow more than one docker-plex to run at a time.

Thanks

**Comment by bhavicp** [comment]
I'm running 6 on a single server - Though i'm using different IPs for each instance. I assume you could do this with only 1 IP as well and assign different external ports to each instance.

**Comment by delaman** [comment]
The second docker-plex does not start.  I think its something to do with the start.sh.  I think it doesnt start the second docker-plex because it thinks its already running.  Maybe I am doing something wrong.

**Comment by bhavicp** [comment]
What do the logs say? docker logs <instance>

**Comment by timhaak** [comment]
Most likely to multiple avahi not wanting to play together.

Unfortunately this is out of the scope of what I'm going to worry about as its not the general case and not something I'm doing.

If life free's up in the future may look at it but not going to happen soon.

Though if you find a fix more than happy to accept a pull request.

Possibly try an build your own image removing the avahi bit from the docker file.

**Comment by choakem** [comment]
is it possable to run your plex-docker twice on the same physical port? as each docker would want to use the internal port of 32400 ???

**Comment by timhaak** [comment]
Yes you can though. you'll have to map different external ports in and not use the '--net="host"' option.

Each running container has its own private ip that it binds 32400 to. The -p 32400:32400 creates an iptable rule that maps the external port onto the internal port of the running container.

If you have multiple external ip's you can also do -p ip1:32400:32400. on one run and -p ip2:32400:32400.

The one problem you may have is the plex applications interface expecting to be able to talk to plex on 32400. Though that is something you'll have to check up with plex as unrelated to the docker container.

**Comment by bhavicp** [comment]
I've tested running around 8 Docker Plex instances on a single machine.
Externally, the ports are mapped from 9000 - 9008, and in settings you
simply change the "Manual port mapping" to this port. Works perfect with
any Plex apps (I.e Plex home theatre, Roku, Plex.tv etc etc)

Auto-discovery won't work, but who needs that since most applications now
use your Plex.tv account to contact your server(s).

Regards,
Bhavic

**Comment by timhaak** [comment]
Awsome :)

**Comment by choakem** [comment]
Tim - Many thanks for taking the time to asnswer this - It's much
appreciated.

Ill invest some time into this weekend.

Many thanks - appreciated.

Michael

**Comment by timhaak** [comment]
@bhavicp are you using dockers newer overlay storage driver? Its supposed to be great for multiple of the same image. Been playing with btrfs one and going  to be moving off to the overlay one.

**Comment by bhavicp** [comment]
Hmmm no, still using AUFS. But thanks for reminding me, I'll hopefully be
able to test it out sometime this week. I haven't really looked into it at
all (there is never enough time in a week!)

**Comment by timhaak** [comment]
Agree :) Busy moving my dev stuff over to it. Though requires kernel 4.0 or later.

**Comment by Joshfindit** [comment]
Just wanted to pop in and say that I was able to successfully run 3 instances on a $10/mo DigitalOcean docker image. (It's only because of the new DO TOR1 that I even looked for this, and I'm glad I did)

    docker run -d --name plex(1,2,3) -h <IP> -v /plex/config(1,2,3):/config -v /plex/media:/data -p 8(1,2,3):32400 timhaak/plex

Excellent work.

**Comment by choakem** [comment]
Lets assume i have 2 external IP addresses of 99.99.99.99 and 100.100.100.100.

What would be a sample start command to run both these instances on the same machine?

Thanks

**Comment by timhaak** [comment]
changet the -p commands to  something like

-p 99.99.99.99:32400:32400

You would then do the run command twice.

Basically when you start plex instead of binding the port to all interface your now only binding the port to the specific ip.

**Comment by choakem** [comment]
Tim: Still playing with dockers......

I have a docker instance running (all good I'm glad to say)

Is it possible to "clone" this instance including the volume so I could run a second instance without the need for re-indexing data etc?

**Comment by timhaak** [comment]
Possibly try copying the config folders?

I have a feeling that will work, though don't know how plex works well enough beyond that.

If that doesn't work I would ask on the plex forums.
