### ISSUE TITLE
locale errors

### ISSUE THREAD

**Issue by tae-one** [timhaak/docker-plex#24]
I getting these errors in the Plex logs. 

Fontconfig warning: ignoring C.UTF-8: not a valid language tag
!!! Plex Transcoder v3.003.15.0503-0439 (c21d4d0, RELEASE, ) !!!

root@plex:/# locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=C.UTF-8

Maybe related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717423

I propose changing LC_ALL="C.UTF-8" to LC_ALL="en_US.UTF-8"

**Comment by timhaak** [comment]
I made some changes yesterday. Please pull and check.

I'll re-open if there are problems.
