### ISSUE TITLE
Can't seem to start plex

### ISSUE THREAD

**Issue by tachang** [timhaak/docker-plex#25]
It just starts and quits immediately.

**Comment by tachang** [comment]
+ GROUP=plextmp
+ mkdir -p /config/logs/supervisor
+ chown -R plex: /config
+ touch /supervisord.log
+ touch /supervisord.pid
+ chown plex: /supervisord.log /supervisord.pid
++ stat -c %g /data
+ TARGET_GID=0
++ cat /etc/group
++ grep 0
++ wc -l
+ EXISTS=17
+ '[' 17 = 0 ']'
++ getent group 0
++ cut -d: -f1
+ GROUP=root
+ usermod -a -G root plex
+ usermod -a -G root plex
/start.sh: line 25: CHANGE_DIR_RIGHTS: unbound variable

**Comment by timhaak** [comment]
Did you build this yourself?

Just asking as the CHANGE_DIR_RIGHTS is set in the dockerfile?

**Comment by timhaak** [comment]
As I haven't heard back from you assuming that there was a problem on your side that's now been fixed. So closing.
