### ISSUE TITLE
please upgrade to plexmediaserver_0.9.12.4.1192-9a47d21_amd64.deb

### ISSUE THREAD

**Issue by kryton** [timhaak/docker-plex#26]
love your work.
if you could upgrade to this version (the latest) the OCD in me will be perfectly satisfied ;-)

regards!
and thanks for building this.

**Comment by timhaak** [comment]
Hi have you done a pull ?

The image should do a rebuild once a day. So at most should be one day out.

**Comment by kryton** [comment]
I think it's because i'm looking at the 'plexpass' release which is a bit sooner, and http://shell.ninthgate.se/ hasn't updated the packages for the 'regular' version yet.
