### ISSUE TITLE
wrong name on docker hub?

### ISSUE THREAD

**Issue by TotalLag** [timhaak/docker-plex#31]
Your instructions show `docker pull timhaak/docker-plex` but docker hub still has your project listed as `docker pull timhaak/plex`?

When I tried pulling, I got the following:

```
root@cfg:~|⇒  docker pull timhaak/docker-plex
Trying to pull repository docker.io/timhaak/docker-plex ... not found
Error: image timhaak/docker-plex:latest not found
```

**Comment by timhaak** [comment]
Thanks for spoting.

Fixed
