### ISSUE TITLE
no supervisord.conf in repository

### ISSUE THREAD

**Issue by scottmckenzie** [timhaak/docker-plex#35]
I get this error when trying to build:
Step 8 : ADD ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf
lstat supervisord.conf: no such file or directory
make: *** [build] Error 1

Can you please add supervisord.conf to the repo?

**Comment by timhaak** [comment]
Hi

Yes sorry not sure how I didn't pick that up.

I've pushed through a new version.

Thanks for spotting.
