### ISSUE TITLE
PMS Version on shell.ninthgate.se is out of date

### ISSUE THREAD

**Issue by mvd7793** [timhaak/docker-plex#37]
Hello! Plex has had server version 0.9.14 out for a bit, but it's not updated on http://shell.ninthgate.se/ where the package is installed from. Is it possible to get that server updated and/or move to one that isn't out of date?

Thanks!

**Comment by timhaak** [comment]
Hi

Yes I see that that version is one behind. I assume the person maintaining that is away on holiday. 

Part of the reason for using that and not pulling directly from plex is that it means I don't have to track when they update their versions.

If you know of a way of doing that automatically I'm happy to move away from  http://shell.ninthgate.se/ and move pulling directly from plex.tv.

**Comment by mvd7793** [comment]
Thanks for the quick reply. :) There doesn't appear to be an obvious pointer to the latest version from their site. A friend with a little more experience is going to look into it later this week.

**Comment by nhandler** [comment]
I made a small fork of this repository that pulls the latest deb directly from Plex. It isn't the cleanest approach, but it should work. The Dockerfile builds fine, but I have not had an opportunity to test it. If someone is able to confirm that the change works as expected without any regressions, I would be happy to submit a Pull Request.

https://github.com/nhandler/docker-plex ([diff](https://github.com/timhaak/docker-plex/compare/master...nhandler:master))

**Comment by sblaauw** [comment]
One option I've run across (but haven't tried) for updating from plex.tv is this script: https://github.com/mrworf/plexupdate

**Comment by timhaak** [comment]
Hmm interesting. I don't have the time to look at it right now but would be nice to remove external dependencies. 

Though I see that the repo has now updated.

Also if your running with --restart always the normal plex update should work.

Though agree not the best option.

**Comment by timhaak** [comment]
@nhandler I like the solution though it will unfortunately be a bit temperamental to them changing the website. 

Though may be the best solution for now. 

I want to sit and look at the script that @sblaauw pointed out first when I have a bit more time.

**Comment by jackwilsdon** [comment]
@timhaak I just wrote a scraper in Python for this exact purpose. I'm not entirely sure how well it will handle changes to the download page but it works as of now.

You can check it out here: [jackwilsdon/plex_version](https://github.com/jackwilsdon/plex_version).

I designed it to be easy to use and it attempts to provide some simple version comparison support too (in `plex_version.version`).

**Comment by timhaak** [comment]
Cool think that's the right way to go long term. Just a bit busy this side so only going to be able look at this in February. 

Need to find a way to make day's longer :)
