### ISSUE TITLE
Permissions issue within plex container during initialization

### ISSUE THREAD

**Issue by kjm0001** [timhaak/docker-plex#39]
Hi, first glad i found this project. Decided to take it for a spin. I noticed the plex container kept restarting and reviewed the docker logs and found the following:

mkdir: cannot create directory '/config/Library': Permission denied
WARNING COULDN'T CREATE /config/Library/Application Support, MAKE SURE I HAVE PERMISSON TO DO THAT!

**Comment by kjm0001** [comment]
I resolved as it was the /config directory setup. thanks again.

**Comment by timhaak** [comment]
Hi

How are you running it? Ie the docker run options.

Is the directory your specifying for the config writable?

It needs to create a directory to put the config files in. 

I've just quickly ran a test this side by deleting the directory of my local version and then re-running and it worked correctly. 

So more likely something on your side.

**Comment by timhaak** [comment]
Cool :). 

Sorry I see you had already replied that it had been fixed before my reply.

**Comment by Meeshoo** [comment]
Sorry to bring up an old thread but I am having the same problem and I'm not really sure what you mean by your solution. Could you explain what you did to fix it?

Thanks

**Comment by neodem** [comment]
Tim had the right questions.. Meeshoo, can you answer them first?

**Comment by Meeshoo** [comment]
Sure thing,

docker run --restart=always -d --name Plex -h Cent -v /Plex/config:/config -v /Plex/Media:/data -p 32400:32400 timhaak/plex

![image](https://cloud.githubusercontent.com/assets/24856690/22830759/99f0885c-ef9f-11e6-9d2f-5ee9ae6e0e5a.png)

To me that seems all okay but I am kinda new to this.

Thanks for the help

**Comment by timhaak** [comment]
@Meeshoo also look at the right's inside the plex directory.

**Comment by flungo** [comment]
@Meeshoo You can try running with `-e CHANGE_CONFIG_DIR_OWNERSHIP=true`. This can slow the starting of the container so if it does then you should be fine to remove it after running at least once with it. Note that this will change the owner of all files in the config directory to the containers `plex` user.

**Comment by Meeshoo** [comment]
@flungo That didn't resolve it :/

And There are only 2 folders (not sure if this changes anything but I created those before running) inside the Plex directory

![image](https://cloud.githubusercontent.com/assets/24856690/22832613/97d552f8-efa6-11e6-898b-8d19e81051a7.png)

**Comment by Coulthon** [comment]
/media/Storage$ sudo docker run -d --name plex --network=host -e TZ="< Europe/London>" -e PLEX_CLAIM="<claim-***************>" -v </var/lib/plexmediaserver>:/config -v </media/Storage/Docker/Plex/transcode>:/transcode -v </media/Storage>:/data plexinc/pms-docker
-bash: :/config: No such file or directory

Any ideas guys, Im using docker for the first time.  But currently thinking its not worth this stress!

Thanks in advance

**Comment by bhavicp** [comment]
`sudo` docker run -d --name plex --network=host -e TZ="Europe/London" -e PLEX_CLAIM="claim-***************" -v /var/lib/plexmediaserver:/config -v /media/Storage/Docker/Plex/transcode:/transcode -v /media/Storage:/data plexinc/pms-docker

Remove all the brackets, general rule for templates, commands etc, always replace <text> with text
