### ISSUE TITLE
 Important: This registry version will not be supported in future versions of docker

### ISSUE THREAD

**Issue by Bodge-IT** [timhaak/docker-plex#40]
Latest pull from Github gets this warning after download:
 Important: This registry version will not be supported in future versions of docker

**Comment by timhaak** [comment]
Hi

Which version of docker are you using?

I think that message is telling you that your trying to connect to the version 1 of the registry api.

Docker hub should be supporting both at the moment though they are going to be deprecating the one soon.

Hence the warning.

**Comment by Bodge-IT** [comment]
Hi Tim,
Using Docker 1.8.3 built in to CoreOs 835.9.0.

Was just a headsup really.

**Comment by timhaak** [comment]
No worries.

I think you may want to update your docker version to 1.9.

The error is from docker and unrelated to the image.

They've created a version 2 for the registry api and are busy deprecating version 1.

With the a newer docker version it should automatically start using the version 2 api if available.

I've tested with docker version 1.9 with a current image and a new pull and both didn't give the error.

Think they want everyone to be using the new api as fast as possible.
