### ISSUE TITLE
Inconsistent use of short-circuits and zero-length string checks in `start.sh`

### ISSUE THREAD

**Issue by flungo** [timhaak/docker-plex#46]
There seems to be an inconsistent use of short circuits in the `start.sh` script:

- https://github.com/timhaak/docker-plex/blob/master/start.sh#L27
- https://github.com/timhaak/docker-plex/blob/master/start.sh#L42
- https://github.com/timhaak/docker-plex/blob/master/start.sh#L64

The three linked above are 3 different ways of doing a zero-length string check. Personally I am a fan of verbosity so would use the `-n` operator but am indifferent when it comes to the short circuit - for me that usually depends on if it's a one line or multiline block afterwards which is actually the opposite of how they have been used in this script.

Seeing as there seems to be more activity on this project now, might be nice to clean up the entrypoint script and get things consistent.

**Comment by timhaak** [comment]
Feel free to go ahead.

Horribly swamped this side. So sort of keeping track but not much time to do anything else.

P.s shout if you do need anything from directly.

Life should start quieting down by next week.

Thanks for what you've been doing.

**Comment by timhaak** [comment]
Pull request merged
