### ISSUE TITLE
use a process manager so a clean shutdown is possible

### ISSUE THREAD

**Issue by stefanfoulis** [timhaak/docker-plex#5]

**Comment by timhaak** [comment]
Yes should but through it together. May look at it this weekend. But am setting up a local openstack first :).

Will see how much energy I have after.

**Comment by stefanfoulis** [comment]
Maybe I'll find the time to add it. Do you have any preferences on what process manager to use?
I've used supervisor in the past, but it's not very good with logs. So I was thinking about trying out S6 (http://blog.tutum.co/2014/12/02/docker-and-s6-my-new-favorite-process-supervisor/).

**Comment by timhaak** [comment]
I'm using supervisor on some other things so would be happy with that.

But if you would like to try another go for it.

**Comment by stefanfoulis** [comment]
I've not had time to do it yet. I'll probably use honcho/foreman for process manager when I get to it. It's simple and already is smart enough to forward stdout from all processes to the main stdout.

**Comment by timhaak** [comment]
I looked a bit more at supervisor and looks like it may not be the best as its not a true init system.

Going to be looking at runit next most probably.

**Comment by delaman** [comment]
Any updates on this?

Thanks

**Comment by timhaak** [comment]
Unfortunately not as yet.

I started to look at s6, but ran out of time.

I could do something with supervisor quickly. 

Would that be ok as a stop gap?

**Comment by delaman** [comment]
yes that will do :)

**Comment by timhaak** [comment]
Done
