### ISSUE TITLE
Fails to connect plex to my account

### ISSUE THREAD

**Issue by WayneSheppard** [timhaak/docker-plex#6]
I have a new server at OVH, with Debian/jessie installed on it.  First thing I do is install docker.io then timhaak/docker-plex.  I start plex successfully with the start command below.  I use putty to connect an SSH tunnel to my server.  Then I browse to the plex installation at http://localhost:8888/web/
I accept the EULA(?) and go to Settings to try to connect the server to my plex account.  I successfully sign in with my credentials, but it fails to connect the server to my account.  The error message is below.

========= command used to start the plex docker install
sudo docker run -d \
     -h 198.245.51.205 \
     -v /data-store:/config \
     -v /:/data-store/downloads/media:/data \
     -p 32400:32400 \
     timhaak/plex

========= Error message in Plex
Connecting your server to Plex allows you to stream media outside your home network.

 Signed in as xxxxxxxxxxxxxxx@gmail.com  SIGN OUT

Signed in to Plex

You have successfully signed your server in to Plex, but we were unable to reach it from outside your network.

If you would like to enable this now, you will need to configure your router or firewall to allow Plex to contact your server. Please refer to our Connecting a Server article for more information.

**Comment by bhavicp** [comment]
Did you try ticking "Manually map my port" option? I find this usually fixes this issue for me.

**Comment by WayneSheppard** [comment]
Well that fixed it right up.  Thank you!

**Comment by timhaak** [comment]
If someone else has a similar problem they should also confirm that port 32400  is open on there firewall and mapped to the server.

**Comment by bhavicp** [comment]
@timhaak For some reason, even though the port is always open (i.e I can access 32400 through the IP to get to the webui) until i ticket "Manually map the port" and put in the exact same port (32400) it won't work! I've had this every single time I've installed Plex, on at least 6 different networks and different servers, where ports are always open. So I've always figured there's a bug or something going on there.

**Comment by WayneSheppard** [comment]
I agree with @bhavicp on this.  I've installed Plex manually several times before on Debian without this happening.  This is my first time using Docker though.

**Comment by timhaak** [comment]
It could be something with the fact that the IP that the docker container has and that plex see's is different to the external IP of the server which is mapped to the docker plex container.
