### ISSUE TITLE
Possibly get https://github.com/jwdempsey/PlexTools.bundle included

### ISSUE THREAD

**Issue by timhaak** [timhaak/docker-plex#61]

**Comment by dsbaars** [comment]
Same as in other issue, using volumes is much better. There are more plugins like Trakttv.bundle which might be useful, but not for everyone. Just use `Plex Media Server/Plugins` and put your desired plug-ins in there.

**Comment by timhaak** [comment]
This was originally from a request to add ffmpeg etc to the base image so that the plugins could be added.

So possibly better way would be to say what tools are missing that people may want.

**Comment by timhaak** [comment]
Closing this for now.
