### ISSUE TITLE
Unable to remove clients

### ISSUE THREAD

**Issue by choakem** [timhaak/docker-plex#63]
I have tested latest version 19.6 and I do not have this issue if I run plex on a non-docker...

I have a server called SERVER.....
I have a friend called JACK..

If I invite JACK as a friend and he accepts - all is well..
If I later remove JACK from my server then he instantly becomes SERVER and still authenticates and I can verify that JACK name has changed to SERVER name and he can still view content although he is no longer a friend....

I created my docker like this:

docker run -d -h plex --name="SERVER" -v /etc/docker/SERVER:/config -v /Media:/data -p 41000:32400 timhaak/plex

I have even created a new docker from scratch and I can repeat this odd behavior at will...

**Comment by timhaak** [comment]
Sounds like a bug in plex?

You'll have to log it with them.

Were not affiliated in anyway.

**Comment by choakem** [comment]
only happens in the docker ... doesnt happen with plex outside the
docker........

**Comment by timhaak** [comment]
It's still a bug in Plex which we won't be able to help with.

Adding and removing a user is done inside the plex application. 

So if removing a user is doing something strange you'll have to follow up with the people who create plex.

It's possible that somehow the way plex  does things causes problems inside the docker image. 

Though as we don't work with the application we have no way to debug errors with it.

If you can track the problem down to something we can change I'm happy to then look at that and makes changes.
