### ISSUE TITLE
Add default values environment variables

### ISSUE THREAD

**Issue by dsbaars** [timhaak/docker-plex#64]
It's not clear that RUN_AS_ROOT and PLEX_DISABLE_SECURITY are true byd default, especially because you mention that RUN_AS_ROOT is dangerous this is a bit confusing

**Comment by timhaak** [comment]
The main reason for that is that not running as root breaks the image for users who don't understand rights.

At some point we did default it the otherway round and it cause too much pain.

My general feeling is it should generally work for the most people. 

Not sure what the correct fix is. Though whatever it is it should just work or at least work in a simple obvious way.

I did have some ideas but start last year life got busy so haven't had much time to put into the image except fixing bugs every now and again. 

I know one of the updates for docker soon should make it that "root" actually doesn't map through to the external hosts root user. (I'm hoping is in 1.12 but don't think so :( )

This should actually deal with most of the larger problems of the insecurity of running as root.

If you have any ideas I would be happy to hear them or if you are keen a pull request. 

Though it has to be something simple that will generally just work.

**Comment by dsbaars** [comment]
I understand the reason, I'll try to create a pull request for the README soon. 

I'm very excited about the functionality you describe (mapping of uid), because LXC has it for quite some time. Could you provide us with some information where you read that?

I mainly added this issue for security awareness, docker is convenient but the security implications are often not or misunderstood.

A possible solution for now (that i know of) is the use of [gosu](https://github.com/tianon/gosu), but that requires some time to understand and implement and has some other implications. If I can find the time I will try and report (and evt. do a pull request) about it.

**Comment by timhaak** [comment]
Added your pull request so closing this for now.
