### ISSUE TITLE
Thumbnails not loading

### ISSUE THREAD

**Issue by avdkamp** [timhaak/docker-plex#67]
I'm having troubles with the thumbnails for my movies. They are not getting fetched automatically.
It seems that they server has the URL's to the images though. (It all worked perfectly without docker hence why I am posting this here.)

![http://i.imgur.com/ezn4XAz.png](http://i.imgur.com/ezn4XAz.png)

The HTML is showing this;
```html
<span class="poster">
    <a class="artwork-option media-poster-container" data-rating-key="http://image.tmdb.org/t/p/original/9OyOBji9K3oMDmGf0irnuVlv4ow.jpg" href="#">
        <div class="media-poster">
            <img class="media-poster-image placeholder-standard">
        </div>
    </a>
</span>
```

**Comment by timhaak** [comment]
This working perfectly this side.

Really unlikely to be a docker problem.

Though it may be a problem in how you have done your run command.

Though without your run command it's quite hard to help. 

How did you run your docker and how did you do your volumes?

If you don't have the config mounted in a volume then you'll loose images on restart, and config.

Also if the rights to the folder don't allow plex to save the images that will also cause a problem.

Also what rights are set on the folders.
