### ISSUE TITLE
Instead of --net="host"

### ISSUE THREAD

**Issue by avdkamp** [timhaak/docker-plex#68]
Instead of using the not so good practice --net="host" parameter it is better to use these ports for plex;

TCP: 32400 (for access to the Plex Media Server) [required]
UDP: 1900 (for access to the Plex DLNA Server)
TCP: 3005 (for controlling Plex Home Theater via Plex Companion)
UDP: 5353 (for older Bonjour/Avahi network discovery)
TCP: 8324 (for controlling Plex for Roku via Plex Companion)
UDP: 32410, 32412, 32413, 32414 (for current GDM network discovery)
TCP: 32469 (for access to the Plex DLNA Server)

Found the ports at: [https://support.plex.tv/hc/en-us/articles/201543147-What-network-ports-do-I-need-to-allow-through-my-firewall-](url)

-p 32400:32400
-p 1900:1900/udp
-p 3005:3005
-p 5353:5353/udp
-p 8324:8324
-p 32410:32410/udp
-p 32412:32412/udp
-p 32413:32413/udp
-p 32414:32414/udp
-p 32469:32469

**Comment by timhaak** [comment]
Your welcome to do that. 

And if you had read the readme you would have seen that it's not the recommended method.

Another reason why you might want to sometimes do --net=host is so plex can see the original IP's (besides bonjour discovery) .

Though it's not a requirement and with plexes latest changes it's needed less.

Anyway this is not a bug. Please read the readme before posting an issue.

**Comment by flungo** [comment]
As Tim explains discovery does not work and that is the main reason you would want `--net=host`. Discovery uses Layer 2 broadcasts and these cannot cross network boundaries (between subnets). With the latest versions of Docker, it is possible to put plex into a network that is bridged with your main network (which is what I do) but this is not documented in the `README` and is probably beyond the scope of the `README`. Maybe it's worth mentioning as a possibility, a pointer in the right direction and an exercise for the reader if they REALLY need auto-discovery but also REALLY don't want to use `--net=host` but this is not a priority.

**Comment by timhaak** [comment]
Though it seems they have been moving more of the discovery into plext.tv. 

Though you need to be signed in for this to work.
