### ISSUE TITLE
Auto Upgrade Not Working

### ISSUE THREAD

**Issue by michaeldown** [timhaak/docker-plex#7]
The contain seems to be unable to update itself to the latest version. Do you know of any way in which I could get the auto update working or a manual method of doing so?

**Comment by timhaak** [comment]
What happens during the auto upgrade. 

Does it just stop?

If it does then I think I know what may be the problem and how to fix.

I'm not using that on this side so haven't hit any problems. (Just pulling the latest build from the index then restarting).

**Comment by michaeldown** [comment]
I have attached a screenshot from my Plex server which illustrates the problem.
![screenshot](https://cloud.githubusercontent.com/assets/8432940/6216094/6f4cb7ba-b5fe-11e4-8e01-96b7d38a5225.png)

**Comment by timhaak** [comment]
Ok that looks more like something on plex's side.

If you can find out why I can look at it.

I do the following every now and again that pulls the latest image update. 

docker pull timhaak/plex
docker rm -f plex
docker run -d -h plex.haak.co -v /conf/plex/:/config -v /mnt/share:/data -p 32400:32400 --name plex  timhaak/plex

**Comment by timhaak** [comment]
@michaeldown  This may be working as had another ticket asking for an init and added supervisord.
