### ISSUE TITLE
Converting to Alpine

### ISSUE THREAD

**Issue by jimlei** [timhaak/docker-plex#71]
Has anyone looked into converting this to use alpine linux? It kinda gets addictive to run small containers after spending some time with it...

I even use a few of your (other) alpine based containers :+1:

**Comment by timhaak** [comment]
I looked very quickly. 

Would most likely need to unpack the deb file to get the pieces.

So should be doable though unlikely to happen soon.

Unless they release on alpine.

**Comment by timhaak** [comment]
As plex now has there own image for docker and most likely going to be moving people over to that one.

I'm going to close this.

https://github.com/plexinc/pms-docker
