### ISSUE TITLE
Multiple Data Locations

### ISSUE THREAD

**Issue by ironlion27** [timhaak/docker-plex#75]
How do i run this with multiple data locations?  I have movies in 1 location and TV in another location.  Thanks.

**Comment by timhaak** [comment]
Couple ways but simplest most likely is change the volume mount to

-v /*your_movie_location*:/data/movie -v /*your_tv_location*:/data/tv

**Comment by ironlion27** [comment]
Thank you!

**Comment by timhaak** [comment]
:) Glad I could help
