### ISSUE TITLE
Mount Error

### ISSUE THREAD

**Issue by ironlion27** [timhaak/docker-plex#76]
Used prescribed volume mount option;

`-v /your_movie_location:/data/movie -v /your_tv_location:/data/tv`

but I'm getting the following error when trying to play anything in the library.  Feels like a permissions error but have chmod 777 recursively the whole area that has my movies and TV to allow any user to access the files.  Please advise.

**Comment by ironlion27** [comment]
forgot the error;

`Please check that the file exists and the necessary drive is mounted.`

**Comment by timhaak** [comment]
Just ran a test and working on this side?

Have you removed the previous files and then re-added the directory (In side the web gui)?

As they are now in a diffrent location?

The simplest may be to wipe your previous config and start clean. (That's what i did with my test)

**Comment by ironlion27** [comment]
Solved!  Process for fixing-

1. Stop Plex container 
2. Mount remote file structure to Docker Server Machine
3. Start Plex container which mounts into the container the local mounted file structure

Issue was I had the docker container running and THEN mounted the remote files to the server's file system.  So spinning up the container those folders were empty.

**Comment by timhaak** [comment]
Ah ok.

Yes if you change the folder strucker the running container will follow the old link. It more like pointer.

Glad you got it sorted.
