### ISSUE TITLE
ninthgate repo might be shutting down

### ISSUE THREAD

**Issue by grashoper20** [timhaak/docker-plex#77]
Not sure where this will go but https://forums.plex.tv/discussion/comment/1243238/#Comment_1243238

"I don't know if i will keep maintaining my repo or not. So please upgrade manualy for the time beeing."

**Comment by timhaak** [comment]
Ok will then need to look into doing the our side via a script.

Currently a tiny bit busy. 

But this was something there was some discussion about doing.

Was more a time things.

Though it now looks more urgent.

**Comment by grashoper20** [comment]
Man I get the busy. :) That's why I figured you'd want the heads up, though today some people where having some trouble so he updated it again so there might be a bit longer.

Here's the script I was playing with for installing the .deb directly. The feed with the plexpass is the same format(and location with a query arg) though requires a auth header with your token so that's going to make builds a bit tricky since ENV get stuffed on the container metadata and you probably don't want to give it to the world.

```
PLEX_URL=${PLEX_URL:-"https://plex.tv/api/downloads/1.json"}
PLEX_JSON=$(curl -s $PLEX_URL | jq -r '.computer.Linux.releases[] | select(.build=="linux-ubuntu-x86_64" and .distro=="ubuntu") | .')
PLEX_DOWNLOAD=$(echo $PLEX_JSON | jq -r '.url')
PLEX_CHECKSUM=$(echo $PLEX_JSON | jq -r '.checksum')
wget -q -O plex_server.deb $PLEX_DOWNLOAD && \
  echo "$PLEX_CHECKSUM *plex_server.deb" | sha1sum -c - && \
  dpkg -i plex_server.deb && \
  rm plex_server.deb
```

**Comment by bruinlax** [comment]
Did the ninthgate repo stop hosting it recently?   my recent docker pulls haven't updated to the most recent distribution.

**Comment by timhaak** [comment]
I have feeling so.

In the middle of some deadlines. 

Going to look at migrating to the script this weekend.

**Comment by timhaak** [comment]
@grashoper20 Busy testing a build based on your script :)

Should hopefully be pushing live in the next hour or so once done some testing

**Comment by timhaak** [comment]
Ok moved to pulling deb file directly from plex.tv

**Comment by grashoper20** [comment]
I actually tried the same thing you did with plex pass but it doesn't actually work. You've got to provide your token in the header to see the pass releases. If you don't you just see the normal plex releases. Also be careful about how you try to handle that there isn't really a method for securely providing secrets to Docker. There's a long standing issue open on the Docker tracker for this because environment variables get stuffed on to the container so you might accidentally give out your token.

**Comment by timhaak** [comment]
Hi

Cool when I tested both gave me the same download. This is with the token as well. 

So I'm assuming they are in sync at the moment.

As I'm using travis to build plex-pass it can handle the secrets. (How we are doing two builds from one repo as hub doesn't support that yet)

Will look at this once I have some more time.

**Comment by timhaak** [comment]
I've added a separate issue to track adding the token so I don't forget.
