### ISSUE TITLE
cannot use --net with -h

### ISSUE THREAD

**Issue by filler** [timhaak/docker-plex#8]
Docs in the README reference combining `--net` along with `-h`.  However recent versions of Docker disallow this.

```
$ APP='plex'
$ HOST=`uname -n`
$ CONFIG='/mnt/plex/config'
$ DATA='/mnt/plex/data'
$ docker run -d --net="host" -h ${HOST} -v ${CONFIG}/${APP}:/config -v ${DATA}:/data -p 32400:32400 plex
docker: Conflicting options: -h and the network mode (--net). See 'docker run --help'.
$ docker --version
Docker version 1.5.0, build a8a31ef/1.5.0
```

**Comment by timhaak** [comment]
Cool don't use it in that form so thanks for picking it up.

Will check what they've changed and sort it out quickly.

Timing was good as was just about to about to add supervisord for someone else's request.

**Comment by thaJeztah** [comment]
Is there any reason to use `--net=host`? This should only be required in exceptional cases and is actually discouraged; https://docs.docker.com/articles/networking/#how-docker-networks-a-container

> It also allows the container to access local network services like D-bus. This can lead to processes in the container being able to do unexpected things like [**restart your computer**](https://github.com/docker/docker/issues/6401). You should use this option with caution.

**Comment by timhaak** [comment]
I agree should not normally be used. 

Part of the problem in this case is the Avahi advertisement of the server that makes it so the players or other servers on the same network are able to pick the server up.

With out --net=host the Plex server is effectively on a different network. 

I personally just add the server IP to the clients. Though as an example there isn't an option to do this on the new beta app on roku (I assume they will be adding it at some point).

I agree that this is not normally best practice. Though in this example there is no other way around this that I can think of. (I haven't really played with Avahi so may be a way of tweaking it to do multiple networks).

Do you know of away around this?

**Comment by timhaak** [comment]
Ok quick scan through its using broad cast so with out the --net=host or using something that relays it you can't do it.

Getting someone to set up a replay defeats some of the advantages of docker. Also require some technical know how.

**Comment by thaJeztah** [comment]
Hm, no I don't have a direct answer to this, but will let you know if I've found something.
Thanks for looking into it though; it's good to know it's there with a reason (I've encountered many cases where people "just" used some settings out of convenience). But I agree, it would be nice if there's a way to make it work without `--net=host`

**Comment by timhaak** [comment]
For now I've removed the -h from the example.

I'm going to close it for now. Can re-open if anyone comes up with a better way of letting Avahi work without using --net=host

**Comment by timhaak** [comment]
@thaJeztah  Agree with not just using a setting :). Especially one like that or the privileged one. 

The only other place i've had to use it is with a proxy one to speed up docker builds when I'm testing. 

To be able to do a transparent iptables intercept and redirect. Due to it needing it.

**Comment by alexjj** [comment]
I've not tried it, but what if you open all the ports plex uses?

https://support.plex.tv/hc/en-us/articles/201543147-What-network-ports-do-I-need-to-allow-through-my-firewall-

-p 32400:32400 -p 32443:32443 -p 1900:1900/udp -p 32463:32463 -p 5353:5353/udp -p 32410:32410/udp -p 32412:32412/udp -p 32413:32413/udp -p 32414:32414/udp
