### ISSUE TITLE
Leave tags for versions on docker hub

### ISSUE THREAD

**Issue by achew22** [timhaak/docker-plex#81]
Is it possible to push to dockerhub with both the tag "latest" and the current plex version (Example: "1.1.4.2757")? My docker is not configured to automatically download versions if the tag latest changes and telling it to upgrade from latest to latest feels a little strange.

Thanks so much!

**Comment by timhaak** [comment]
Unfortunately not at the moment.

**Comment by achew22** [comment]
Not to keep bothering you (sorry) but is there a technical reason for this? Could I send you a pr that leaves the tag in your script?

**Comment by timhaak** [comment]
Explain to me how you think that would work?

**Comment by achew22** [comment]
I've been wrong about a great many things, but I believe you should be able to do this.

```shell
# Do the things that generate the docker image and tag your latest
docker tag timhaak/docker-plexpass:latest timhaak/docker-plexpass:v1.1.4.2757
docker push timhaak/docker-plexpass:v1.1.4.2757
```

This should be both instantaneous and take up <1kb of storage since all it will do is generate an additional metadata.json file in the .tar.gz file.

What do you think about that?

**Comment by achew22** [comment]
I would LOVE to send you a pull request but I think this will require mucking with the UI of dockerhub. Sorry!

Just a WAG, but [it seems](https://docs.docker.com/docker-hub/builds/#/create-an-automated-build) to imply that you can use a regular expression to match a tag in git. You could use a git tag to indicate the version and then give it the name [{sourceref}](http://stackoverflow.com/a/37509565). Sorry I can't do better than a totally unsourced stackoverflow answer!

**Comment by achew22** [comment]
To push tags from git you should be able to do basically the same trick:

```
# Hack on stuff and make it awesome (thanks for doing that BTW!)
git commit
# Do git commit stuff
git tag v1.1.4.2757
git push origin v1.1.4.2757 # Assuming you're using origin as the remote for your github repo
```

If you wanted to get really fancy you could do a commit message that had the release notes for plex with an annotated tag (`git tag -a v1.1.4.2757`) but that would probably be overkill

**Comment by timhaak** [comment]
Yes though that would be a manual process each time plex updates the app.

This being the main reason that it's not done.

I'm not connected with plex so me or someone one would have to login and check if its changed on their site.

If it had we would then need to tag the commit.

There are some ideas that could be looked at to script this. 

Though it would then have to be running on a server logging in and checking. Though at this moment I don't have the time to do this.

Currently the system just grabs the latest version and uses that, but doesn't care what version it is.

We've just recently updated that part to use the plex.tv site to pull the version as apposed to using nthgate ppa as he's deprecating it.

So its possible to do now. (Previously would just install plex so no way to know the version)

But would require updating the DockerFile to have the version specified. 
Then writing a script that checked the version every so often. When it detected a change. It would then have to update the dockerfile. Push and tag into github. This should then trigger a build on hub.docker.com (would have to have updated it to look at tags).
