### ISSUE TITLE
Plex Crashing every few minutes on FreeNAS 10

### ISSUE THREAD

**Issue by anantbhula** [timhaak/docker-plex#84]
Hi I am currently testing out Plex container on FreeNAS 10. After installation it worked fine but past 24 hours it has been crashing every few minutes and turn of itself.
Here is what the console says:

> AFTER
> PLEX_TOKEN :                                                                                                                                                                    
> PLEX_USERNAME :                                                                                                                                                                       
> PLEX_PASSWORD :                                                                                                                                                                       
> 6 3000 /config/Library/Application Support                                                                                                                                            
> 8192                                                                                                                                                                                  
> ****** PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.1.4.2757-24ffd60/PLEX MEDIA SERVER/79775119-420b-514c-23
> f66d63-1629a0b4.dmp                                                                                                                                                                   
> Bus error                                                                                                                                                                             
> PLEX_TOKEN :                                                                                                                                                                          
> PLEX_USERNAME :                                                                                                                                                                       
> PLEX_PASSWORD :                                                                                                                                                                       
> AFTER PLEX_TOKEN :                                                                                                                                                                    
> PLEX_USERNAME :                                                                                                                                                                       
> PLEX_PASSWORD :                                                                                                                                                                       
> 6 3000 /config/Library/Application Support                                                                                                                                            
> 8192                                                                                                                                                                                  
> ^PWARNING: ENABLED NONE CIPHER                                                                                                                                                        
>                                                                                                                                                                                       
> restart=always                                                                                                                                                                        
> ^PWARNING: ENABLED NONE CIPHER                                                                                                                                                        
> WARNING: ENABLED NONE CIPHER                                                                                                                                                          
> ****** PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.1.4.2757-24ffd60/PLEX MEDIA SERVER/3c0c723a-3a50-1b6b-21
> 2104f0-23f7e20b.dmp                                                                                                                                                                   
> Bus error                                                                                                                                                                             
> PLEX_TOKEN :                                                                                                                                                                          
> PLEX_USERNAME :                                                                                                                                                                       
> PLEX_PASSWORD :                                                                                                                                                                       
> AFTER PLEX_TOKEN :                                                                                                                                                                    
> PLEX_USERNAME :                                                                                                                                                                       
> PLEX_PASSWORD :                                                                                                                                                                       
> 6 3000 /config/Library/Application Support                                                                                                                                            
> 8192                                                                                                                                                                                  
> WARNING: ENABLED NONE CIPHER                                                                                                                                                          
> ^PGot nothing for: Nashville S01 Special the Whole Story                                                                                                                              
> __code__:661: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.                                 
> ****** PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.1.4.2757-24ffd60/PLEX MEDIA SERVER/0832df53-198e-019e-71
> 31a3d9-21b4702a.dmp                                                                                                                                                                   
> Bus error                                                                                                                                                                             
> PLEX_TOKEN :                                                                                                                                                                          
> PLEX_USERNAME :                                                                                                                                                                       
> PLEX_PASSWORD :                                                                                                                                                                       
> AFTER PLEX_TOKEN :                                                                                                                                                                    
> PLEX_USERNAME :                                                                                                                                                                       
> PLEX_PASSWORD :                                                                                                                                                                       
> 6 3000 /config/Library/Application Support                                                                                                                                            
> 8192                                                                                                                                                                                  
> Got nothing for: Nashville S01 Special the Whole Story                                                                                                                                
> __code__:661: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.                                 
> WARNING: ENABLED NONE CIPHER

**Comment by timhaak** [comment]
Hi

Freenas which is based on bsd uses a diffrent technology for it's "containers" called jails.

This repo is for a docker plex image that would run on linux i686 (Could possibly built for arm).

You'll have to contact the people who do the bsd jails image of plex for freenas.

You could have a separate server for docker and freenas and have freenas just provide network storage. (Current this is how I do it at home.)

Your other option is to ask on the plex forums. (Were not connected with plex)

**Comment by anantbhula** [comment]
That's what i have as well plex is running under docker host in FreeNAS 10.
Thank you for the info
