### ISSUE TITLE
Issues with PLEX_ALLOWED_NETWORKS

### ISSUE THREAD

**Issue by shotah** [timhaak/docker-plex#85]
Allowed Networks does not seem to be filtering in this build. I'm also having an issues with setting it as PlexPas Command I'm adding to docker run '-e PLEX_ALLOWED_NETWORKS=192.168.1.0/24'. Help or a fix would be great!

**Comment by timhaak** [comment]
Hi

You may also need to add the docker network.

**Comment by shotah** [comment]
I have added it. '--net="host"' to enable Xbox discovery. the Plex_allowed_networks is "192.168.1.0/255.255.255.0,172.17.0.1/255.255.0.0". I can try again as I think in my test I was doing a slightly different Docker network.

**Comment by timhaak** [comment]
Ah ok if you've added --net="host" no need to add the docker ranges.

I'll have to test this latter and see if I can see a problem. In the middle of something right now.

Let me know if you find anything in the mean time.

**Comment by shotah** [comment]
No worries, it is still an issue though. Currently using my router as my dhcp and dns. I imagine most home users are doing the same. Just curious if it has anything thing to doing with PAT'ing but, I don't even be able to set the network to a /32 to require a logon to connections from https from the outside.

**Comment by robertbarrett** [comment]
I thought I was having a similar issue to @shotah . I think I may have nailed it down.

For me, Plex did not seem to be filtering, all remote hosts could connect without authentication.

I am not at home now to test, but just noticed PLEX_DISABLE_SECURITY defaults to 1 (remote security will be disabled)

If you don't specify -e PLEX_DISABLE_SECURITY=0, does PLEX_ALLOWED_NETWORKS have any effect?

**Comment by robertbarrett** [comment]
@shotah, in case you missed what I wrote in the other issue, you might want to check if it's the same problem I had

Check Preferences.xml for the value for disableRemoteSecurity if it is 1 do the following:

1) stop the plex container.

2) edit Preferences.xml to read disableRemoteSecurity="0"

3) start the plex container

**Comment by shotah** [comment]
So that did not work. I did go through the process of removing all of the docker images. Deleted my config files and started over. At that point I was able to go into Preferences.xml and set the configuration, which in my opinion should be a default. Maybe in my original testing I corrupted one of the files. *shrug* but it's working now!. Thanks guys!

**Comment by shotah** [comment]
Looking back through my issues I saw this still open. It was fixed with one of their updates. This can be closed.

**Comment by timhaak** [comment]
Thanks
