### ISSUE TITLE
fix for token plexpass not working

### ISSUE THREAD

**Issue by boistordu** [timhaak/docker-plex#86]
`Authenticating...ERROR: Username and/or password incorrect`

I try to put the password and login even in the dockerfile in place of build-arg but still doesn't work. Did you try your fix? is It working for you? I'm not sure that the variabes are well passed. Anyway the curl command works so it's not a problem of username nor email nor password on my part.

**Comment by boistordu** [comment]
it's just to see if you have problems or not with your authentification, to have a comparaison point with me. because if it's working for you then it's certainly a problem with my bad char or something.

**Comment by boistordu** [comment]
my problem as been solved by using a config file in place of build-arg... I have modify then the dockerfile, I don't if you want a pull from me?

**Comment by timhaak** [comment]
It's working for me both via a travis build that is pushed to docker hub and when I did a local build.

So not really sure why it's breaking for you.

Though if you want to send me a pull request of your changes.

There may be follow a better pattern in which case I would be happy to merge.

**Comment by boistordu** [comment]
mscreations have modified the code from plexupdate becasue of my problem so no need of config file .
