### ISSUE TITLE
Connecting to devices on Local network

### ISSUE THREAD

**Issue by neodem** [timhaak/docker-plex#90]
I've got an appleTV that used to work when I had a physical server running the plex server but now in the docker I'm having connection issues. I'm pretty bummed since I really love your docker container implementation. I've tried various settings of allowedNetworks and disableRemoteSecurity with no luck. I've also tried --network='host' with no luck. Do you have other ideas?

**Comment by Joshfindit** [comment]
@neodem Are you hosting it on OSX?

**Comment by neodem** [comment]
yes

**Comment by timhaak** [comment]
Just to confirm it's not a problem with discovery.

Can you set the server ip in the plex app. (normally under advanced
settings if I remember correctly)

**Comment by neodem** [comment]
Josh, thank you. That worked! I made a PR in case Tim wants to add them to the Dockerfile.

Thanks again to all!
