### ISSUE TITLE
Multiple Plex Servers

### ISSUE THREAD

**Issue by Codgedodger** [timhaak/docker-plex#94]
I know this has been asked before but I need help with a walk through. I was given a set of IPs when I got my server setup. I'd like to have multiple Plex servers running on my server. I already have a plain one installed and running just fine. I'd like to have the other Plex server run though Docker on a different IP the company gave me. 

They gave me these IPs. 
198.xxx.xx.232/29

My server IP now has 198.xxx.xx.234 
Could someone help me with walking me through with another docker for my Plex servers? I'd be willing to donate via Paypal at this point.

**Comment by danbo** [comment]
I plan on doing this shortly, if it works, I'll help you out.

**Comment by timhaak** [comment]
@Codgedodger that range should give you 6 ip's I think.

With port mount command just add the ip in front and then ":". This will bind then to port and ip. (Normally it's a wild card so binds to all ip's). 

-p 198.xxx.xx.234:32400:32400

Just remember to have different config directories for each.

**Comment by Joshfindit** [comment]
Related note: if your docker host supports `net=host`, it's just a matter of assigning the ip to each container and letting it expose the ports.

**Comment by dmcharpentier** [comment]
If you have a router that supports multiple ip's then you can use that to do all the routing as well by making sure all the wan traffic from that system uses that external IP.

**Comment by timhaak** [comment]
Assume this is sorted as no further replies
