### ISSUE TITLE
Docker PLEX with NAS

### ISSUE THREAD

**Issue by luis4ndre** [timhaak/docker-plex#98]
Hi,
I would to know if is possible use a NAS with this container?
If yes, how?

Thanks.

**Comment by timhaak** [comment]
I don't fully understand the question.

What do you mean by use a NAS?

If you mean can you have the media files on a NAS. Then yes you just mount them to your server and then follow the normal process just pointing the volume at the mounted folder.

If you mean can you run the docker image on the NAS? It would depend on which NAS you are using.

**Comment by flungo** [comment]
It is going to depend on your NAS. Please refer to the documentation from your NAS manufacturer on running Docker containers (if that is a supported feature) then you should be able to map the commands required to run from the command line into the options made available by your NAS.

There is nothing in the image which would restrict it from running on a NAS that supports Docker, though. If you find there is something which restricts you from doing so, please report it.

If instead, you wanted to run this on a machine other than your NAS but utilise your NAS storage, mount a directory from the NAS onto your host before creating the container and adding that mount as a volume.

**Comment by luis4ndre** [comment]
Sorry,
I didn't express myself very well, I'm running a Docker in a PC (Linux or Windows), but I can't access a network folder inside a container.

**Comment by timhaak** [comment]
Are you pointing to the mounted folder location with the volume mount option (-v)?

Also, check the rights of the folder that can sometimes cause problems. Try using the RUN_AS_ROOT option (See the readme).

**Comment by timhaak** [comment]
Assume  this is sorted as no further replies closing
